[RFC] Implementations may not deprecate a field that the interface hasn't deprecated
graphql/graphql-spec pull request #1053
Opened 2023-11-09 12:02 UTC by benjie

This PR addresses a spec validation omission; if an interface field is not deprecated then any implementation of that interface field should also not be deprecated. I.e. the following schema _should_ be invalid, but before this PR it is valid:

```graphql
interface Node {
  id: ID!
}

type Foo implements Node {
  id: ID! @deprecated(reason: "...")
}

type Query {
  foo: Foo
}
```

To solve this, either the deprecation should be removed, or the `id` field on `Node` should _also_ be deprecated:

```graphql
interface Node {
  id: ID! @deprecated(reason: "...")
}
```

Relevant action item: https://github.com/graphql/graphql-wg/issues/1331

2024-12-05 18:56 UTC, fotoetienne commented
Should the graphql-js impl be part of a major release?

2024-12-05 19:11 UTC, mjmahone approved these changes

2024-12-05 19:14 UTC, mjmahone commented
One potential wrinkle to this: we don't really have deprecated interface implementations.

Like, maybe I'm deprecating a field because I will *not* be implementing an interface in the future. What I'm really trying to say is:
```
interface Node {
  id: ID!
}

type Foo implements Node @deprecated(reason: "Node is terrible for this purpose") {
  id: ID! 
}

type Query {
  foo: Foo
}
```

2024-12-05 19:15 UTC, leebyron approved these changes
suggest rewriting to:

- avoid directly referencing directives, but just the deprecated status directly.
- if / then to avoid the negative

2024-12-05 19:15 UTC, leebyron commented on spec/Section 3 -- Type System.md
> +       the `@deprecated` directive must not be applied to {field}.
```suggestion
    6. If {field} is deprecated then {implementedField} must also be deprecated.
```

2024-12-08 20:54 UTC, michaelstaib approved these changes

2024-12-12 21:35 UTC, fotoetienne commented
> maybe I'm deprecating a field because I will not be implementing an interface in the future.

I think @mjmahone has a valid point. Perhaps we don't want clients to do this anymore:

```graphql
... on Foo {
    id
}
```

but this is still ok
```graphql
... on Node {
    id
}
```

Marking `id` on foo as deprecated would indicate this.

2024-12-12 21:38 UTC, fotoetienne requested changes
On further reflection, I'm thinking that this validation isn't needed. It doesn't bring enough benefit to warrant removing some deprecation capabilities.

2024-12-13 10:00 UTC, benjie commented
@fotoetienne I think the general intent of deprecation (and specifically the `includeDeprecated` feature in introspection) is that you should be able to represent a schema with all deprecated entities removed and that schema should still be valid. Without this rule, this is not the case - if you remove the deprecated fields then `Foo` no longer implements `Node`, and the "not deprecated" schema is now invalid.

If and when we support deprecation on interface implementation as Matt suggest, this rule can be changed such that _either_ the interface field is deprecated _or_ the implementation of this interface is deprecated.

2025-01-09 19:41 UTC, benjie commented
Discussed at tonights WG; we boiled it down to this:

**If you remove everything deprecated from a GraphQL schema, should the resulting schema be valid?**

Consensus was yes, @michaelstaib expressed it as something along the lines of: if you're building a new client to a GraphQL schema, you don't want to use any of the deprecated fields so you should be able to just use a schema with everything deprecated removed.

Do you agree with this guiding principle to deprecation, @fotoetienne?

If so, but you feel this is removing the deprecation capability of deprecating a field where you plan to remove the type from an interface, then perhaps we need to pair this with a spec change that enables deprecation on object type interface implementation?

2025-01-10 13:31 UTC, fotoetienne commented
👍That makes sense. Once we support object/interface deprecation, we can revisit the use case.

2025-03-08 07:35 UTC, JoviDeCroock approved these changes

2025-04-01 15:41 UTC, benjie commented
It breaks the guiding principle for deprecation which is that if you remove everything that is deprecated then the resulting schema should still be valid. Implementing this rule should not break any client applications, and is easy to address within the schema by either deprecating the interface field or un-deprecating the object field depending on your intent.

2025-04-01 16:17 UTC, martinbonnin commented
Principles are good of course but I also like it when changes are rooted in real life use cases, helps making a case that the principles are still up to date, solving concrete issues, etc... 
In all cases, LGTM, was mostly curious.

2025-04-03 08:23 UTC, BoD approved these changes

2025-04-03 19:05 UTC, mjmahone approved these changes

2025-05-01 17:49 UTC, merged