Update criterion match in input union RFC
graphql/graphql-spec pull request #784
Opened 2020-09-30 11:47 UTC by dfreeman

Currently for **Criterion F** (`Migrating a field to a polymorphic input type is non-breaking`), the tagged unions option is listed as meeting that criterion on the grounds "No migration required, as this pattern is already possible".

This seems to actually be an answer to **Criterion I** (`Input unions should be easy to upgrade from existing solutions`), which lists the same explanation.

As I understand criterion F (and what the responses for the other proposals seem to be addressing) isn't about migrating from other input union approximations today. Rather, in a world where _some_ input union proposal is a part of the spec, it examines migrating an input that currently only accepts a single type to one that accepts a union.

For example, given these types:

```gql
input CatInput {
  name: String!
  age: Int!
  livesLeft: Int
}

input DogInput {
  name: String!
  age: Int!
  breed: DogBreed
}

input AnimalInput @oneOf {
  cat: CatInput
  dog: DogInput
}
```

Consider migrating to an input union for the `animals` argument:

```gql
type Mutation {
  # From this:
  logAnimalDropOff(location: String, animals: [CatInput!]!): Int

  # To this:
  logAnimalDropOff(location: String, animals: [AnimalInput!]!): Int
}
```

This kind of situation is what the other proposals appear to be addressing in their explanations of how they do (or don't) meet Criterion F. With tagged unions, a valid `CatInput` is not a valid `AnimalInput`, so changing `pet` from a simple input type to a polymorphic one is a breaking change.

2020-09-30 12:41 UTC, benjie requested changes
:+1: 

Please also update line 905 (in the "Evaluation Overview" table)

2020-09-30 14:08 UTC, dfreeman commented
@benjie Thanks for catching that! Updated.

2020-09-30 14:38 UTC, benjie approved these changes

2020-09-30 18:55 UTC, binaryseed commented
I think this isn't so clearly a failing grade, I'd suggest it's both passing and failing. But I'm going to merge this anyway :)

2020-09-30 18:55 UTC, merged

2020-10-01 12:57 UTC, dfreeman commented
> I'd suggest it's both passing and failing. But I'm going to merge this anyway :)

@binaryseed Can you unpack that a little? It seems like a clear 🚫 to me on this specific criterion, but more to the point, if there's not consensus on whether this was a correct change, I'd honestly rather have seen it not get merged.

The point of laying out the criteria in this RFC document is to help figure out objective metrics to weigh the various options against, right? This kind of ambiguity feels like it undermines that effort, and given how complex the design constraints are here, I'd hate to be contributing to that 🙂