Editing the broken links
graphql/graphql-spec pull request #874
Opened 2021-06-10 20:23 UTC by RanabirChakraborty

There were few broken links in the README file. Changed those.

2021-06-11 12:44 UTC, benjie requested changes
Looks good to me; just one change to rollback then it gets my +1 :+1: Thanks for submitting these changes :raised_hands:

2021-06-11 12:55 UTC, RanabirChakraborty commented on README.md
> +The latest draft specification can be found at [here](https://graphql.github.io/graphql-spec/draft/)
Thanks! done

2021-06-11 20:59 UTC, benjie approved these changes

2021-09-02 21:40 UTC, merged

2025-06-26 19:18 UTC, Muaytie666 reviewed
7763547408