provided explicit ref to Value Completion section
graphql/graphql-spec pull request #982
Opened 2022-08-03 05:41 UTC by rivantsov

the current version mentions executor (what is that by the way?), and then:  
> this is covered in that section 

which section is not clear, we do not have 'executor' section. I suggest some rephrasing, and remove 'executor' - it is not an explained concept in the spec.

2022-08-03 07:11 UTC, michaelstaib commented on spec/Section 3 -- Type System.md
> +[6.4.3 Value Completion](#sec-Value-Completion) in Execution section.
I am not sure about pointing to the section numbers like that. 

I think referring to it more like:

```suggestion
executor, so this is covered in the sub-section [Value Completion](#sec-Value-Completion) in Execution section.
```

But the whole sentence now does not read so well anymore :)

2022-08-03 07:30 UTC, benjie requested changes

2022-08-03 07:30 UTC, benjie commented on spec/Section 3 -- Type System.md
> +[6.4.3 Value Completion](#sec-Value-Completion) in Execution section.
I think we can get away with a much smaller edit:

```suggestion
executor, see [Value Completion](#sec-Value-Completion).
```

2022-08-03 07:35 UTC, michaelstaib approved these changes

2022-08-03 07:39 UTC, benjie approved these changes

2022-12-07 23:49 UTC, mjmahone approved these changes

2022-12-08 01:05 UTC, merged